[toolchain]
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-gnu", "thumbv8m.main-none-eabihf", "thumbv7em-none-eabi", "thumbv7m-none-eabi"]
components = [ "rust-src", "llvm-tools-preview", "rustc-dev" ]
channel = "nightly-2025-11-01"
